stages:
  - lint
  - build

variables:
  NODE_ENV: development

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

eslint:
  stage: lint
  image: node:18
  script:
    - npm ci
    - npm run lint

build:
  stage: build
  image: node:18
  script:
    - npm ci
    - npm run build
  needs: ['eslint']
